Feature/delete workspace
labelflow/labelflow pull request #667
Opened 2021-12-17 11:53 UTC by bbenoist

# Feature

## Work performed

## Results

## Problems encountered

## Caveats

## Resolved issues

## Newly raised issues

2021-12-23 15:30 UTC, etiennedupont requested changes
The feature works overall, I just noticed that you can't create a workspace when one with the same name was deleted already (see remark inside the code). 

I'm not sure to understand the need to move some logic from common-resolvers to the repository side directly? I think that our goal was initially to keep repositories as simple as possible to anticipate backend plugins in the future.

As a side note:
I think there are some important differences in philosophy and structure as compared to the rest of the codebase, which makes me think that we probably need to (decide and) enforce some guidelines. e.g:
- Usage of context vs querying vs passing props down (ex: typescript/web/src/components/settings/workspace/context.ts)
- Functional programming vs Object-oriented (ex: typescript/db/src/utils/stripe.ts)
- Files structure `x.y.ts` vs `y/x.ts` (ex: typescript/web/src/components/workspace-name-input/workspace-name-input.stories.tsx)

In particular, it feels a bit messy to me to see such different file structures cohabiting together, I think we should try to avoid that.
<img width="342" alt="Screenshot 2021-12-23 at 15 46 41" src="https://user-images.githubusercontent.com/23740011/147257421-11056e34-3c27-435e-9f4d-b938ab4d41cd.png">

2021-12-23 15:30 UTC, etiennedupont commented on typescript/web/src/components/settings/workspace/danger-zone/delete-workspace-warning.tsx
> +            <ListItem>Every members will lose access to the workspace</ListItem>
```suggestion
            <ListItem>Every member will lose access to the workspace</ListItem>
```

2021-12-23 15:30 UTC, etiennedupont commented on typescript/db/src/repository/workspace.ts
> +    data: { deletedAt: new Date().toISOString(), slug: `${slug}-${data.id}` },
You also need to change the `name` of the workspace, or you'll end up having conflicting name issues (see general comment)

2021-12-23 18:40 UTC, bbenoist commented on typescript/common-resolvers/src/utils/validate-workspace-name.ts
> +];
I've only moved an existing constant (which was called `forbiddenWorkspaceSlugs`) 😉 

About your remark, the problem here is that we're in the `common-resolvers` package which is not aware about the routes defined via the `pages` file stucture in the `web` package (which `common-resolvers` cannot depend on).

2021-12-23 18:47 UTC, bbenoist commented on data/mutations.graphql
> +  deleteWorkspace(where: WorkspaceWhereUniqueInput!): Workspace
It's by design. I've made it so you cannot access deleted workspaces from outside of the workspace repository.
The fact that we don't actually delete workspaces is an internal implementation detail (_based on performance problem assumptions but that's another debate_). It's not really an API feature.

2021-12-23 18:57 UTC, etiennedupont commented on typescript/common-resolvers/src/utils/validate-workspace-name.ts
> +];
Yes I was rather thinking about doing an action in the CI, which is aware of the whole repo, but that's a bit intricate for the reward

2021-12-23 18:58 UTC, etiennedupont commented on data/mutations.graphql
> +  deleteWorkspace(where: WorkspaceWhereUniqueInput!): Workspace
Since you explicitly use this field in `db`, that causes typing errors, because the repository types are unified

2021-12-24 14:26 UTC, bbenoist commented
Thank you for this code-review!

I'll fix the issue occurring when a workspace has already been deleted. Nice catch!

Below are my answers to the general remarks you've submitted.

Indeed, they are parts which will have to be included in wider discussions but I wanted to leave detailed-enough explanations here so that anyone can share their mind if they see something wrong.

## Placing some logic in repositories instead of resolvers

Overall, the problem is that we don't have a business layer between the resolvers and the repositories.
As an example, in a common SOLID server architecture, you have some `Service` classes which are reusable everywhere across the other services, resolvers and repositories.
These service layers are responsible of the business logic and the resolvers layers are only responsible of exposing it to the API protocol(s) we need to support. They wouldn't call any repository directly.

More concretely you would have: `WorkspaceResolver -> WorkspaceService -> WorkspaceRepository`

It's kind of long to explain all of the benefits but here are some good frameworks based on such architectures which explains how it works:
  * [Nest](https://docs.nestjs.com/providers)
  * [Loopback](https://loopback.io/doc/en/lb4/Inside-LoopBack-Application.html#api-implementation)

Since we don't have such an intermediary layer, I had to choose between placing logic in the repositories or in the resolvers.

Below is the rationale behind each choice.

#### `deletedAt`

Because I had to implement the `deletedAt` mechanism, I had a choice to make:

1. Check whether `deletedAt` is `null` everywhere we use the workspace repository (i.e. in all calls to `get`, `list`, `update`, etc.). Not even in the repository resolver but everywhere it's being used.
2. Implement the verification at the repository-side and make it so workspaces with `deletedAt` being set are considered as inexistent from outside.

Since we only use of this property because of low-level performance considerations, and because solution 1 would require a lot more code everywhere in the resolvers codebase, I've decided to go over solution 2.

#### `createdAt` / `updatedAt`

As for the `deletedAt` mechanism, these properties are low-level values whose management has to be centralized at a low-level so that we don't miss setting and updating them. In some systems, these values are even set automatically by the engine.

#### Stripe

This one is clearly debatable :sweat_smile:

At the beginning, I wanted the repository to be responsible of the `slug` management. Since we consider slugs as being like a unique identifier derived from the `name` property, I wanted to enforce that rule by calling the `getSlug` function at the `create` and `update` (only if needed) steps of the repository.

However, as Stripe accounts needs the workspace slug to be created, I had the choice to:

1. Wait for the workspace to be created by the repository and get the resulting slug. Then, create the Stripe account and send an update to the repository with the Stripe customer ID.
2. Create the Stripe account from the repository after the slug got generated and before the workspace gets created in the DB.
3. Same as 2 but with a callback as argument to the repository.

I've chosen 2 but I agree that it's not a perfect solution. Stripe shouldn't have to be used at such a low-level.

To continue with the idea of the `Service` layer, this is typically the kind of things (slug + Stripe) that I would have put in the `create`, `delete` and `update` functions of a `WorkspaceService`.

## Usage of context

When you want to split a component into multiple parts, you often have to forward some state values and some functions acting on these values.

While passing-down props is the simplest, it can be very verbose when you have a deep level of decomposition. Your code becomes complex if you want to forward only the necessary props to each part of your DOM.
One way to simplify this is to use a context such as React.Context or the one provided by Zustand.
By using a context, you only use the values and functions where necessary and don't have to forward props anymore. Overall, the code gets cleaner and simpler to understand.

#### Why did I use React Context over Zustand

While I could have used Zustand to manage the shared states, I wanted the code to be as functional and immutable as possible.

The problem with the way zustand works is that:
* It relies on a singleton. You can't clearly decide of the scope of your context.
* [Without wrapping a factory function into a React Context, it cannot have initial values](https://github.com/pmndrs/zustand#react-context) (unless you rely on `useEffect` and trigger re-renders).
* Unless you use some hacks with `useEffect`, you cannot share values coming from hooks.

As such, I've decided to go with the most pure (functionally speaking) solution which is having a custom context provider where all of the values computation is made.

Thanks to this, the whole dependency chain for calculated values remains centralized, purely functional and immutable. And it would not trigger unnecessary re-renders.

## Functional programming vs Object-oriented programming

I don't see the point of enforcing the use of one vs another. We must use the paradigm which fits the most our needs. Sometimes, it's cleaner to use OOP instead of passing an object to every function acting on it. That's kind of the same problem than with using contexts vs props propagation :wink:

For the Stripe class, I've decided to go this way because :

* We have to take care of the Stripe pointer. Managing it in a class enforces the usage of Stripe in isolated, single-responsibility functions.

* It leaves the possibility to remove the usage of a singleton without having to refactor the whole code.

* That's kind of the standard way I'm used to architecture such things. I have `Service` classes which can be injected (via dependency-injection) to other `Service`, `Repository` or `Resolver` classes.

Given that we use a singleton for now, I can still keep it "functional" and change the code to avoid the need to pass by an object. It's not that important...

## File naming

One of the things which got me loose time when working on this PR was that there was 3 files with the same name (for the component, the test and the story). Combined with the long path where the file was placed, I couldn't determine which file was the one I wanted to open when using `Cmd+P` in VS Code. I had to open one of the suggested files, see its content and reopen another one if it didn't match the first time, praying that the second time will end up with the file I initially wanted.
Meanwhile, when using the `.test` and `.story` convention, I could navigate to each file without having to lose time checking in which directory it is located.

As I've renamed the test and storybook files, the `__tests__` and `__stories__` directories became meaningless since they only contained 1 file whose name was already distinct-enough from the component file to be moved alongside it.

Because they are unit-tests and "unit-stories", I think that it makes sense to keep them alongside the component they cover. Moreover, it simplifies the directory tree structure.

About the need to have a common rule, I'd say that while I would keep the `__tests__` directory for complex tests, I think that it would be simpler and cleaner to use such a convention for the unit-tests since they should be tied to a single source file. You have a better navigation and it kind of enforces consistent file names and the single-responsibility principle.

Following the same way of thinking, the `.context` extension has been used because it represents the context of the top-level component. As for `.test` and `.story`, I find it appropriate to share the same base name than the component it manages instead of just calling it `context.tsx`.

And the `.query` and `.mutation` have been used because it would allow [...]

2021-12-28 11:14 UTC, merged