Add images workspace consumption based on plan
labelflow/labelflow pull request #925
Opened 2022-03-01 15:23 UTC by Jordanlelay

## Work performed

## Results

## Problems encountered

## Caveats

## Resolved issues

## Newly raised issues

2022-03-07 10:51 UTC, Jordanlelay commented on typescript/web/src/pages/[workspaceSlug]/settings.tsx
> +export const GET_WORKSPACE_DETAILS_QUERY = gql`
Remaining code from earlier, nice catch 👍

2022-03-07 16:59 UTC, bbenoist requested changes
@Jordanlelay I've readjusted a little bit the code of the Billing component. Nothing critical but you can take a look at the commit description for details.

- [ ] Other than that, there remains 1 issue to be resolved: since you've removed the Enterprise WorkspacePlan, it's needed to create a DB schema migration and apply it on our dev DB just before we merge this PR in main.

2022-03-08 19:55 UTC, bbenoist commented
@Jordanlelay As suggested during the last DSM, and because this PR is OK except for the migration part, I propose you to:
1. Rebase this PR on the latest revision of `main` and fix the conflicts
2. Squash the 3 commits of this PR into a single commit (_with `(#925)` at the end of the title_) and force-push the `feature/plan-consuption` branch.
3. Squash the commits of `feature/trial-period` (#913) and force-push the commit.
4. If the CI goes green on both PR, merge `feature/plan-consumption` into `feature/trial-period` (#913)
5. Push the changes of `feature/trial-period` and make sure that the CI is green.
6. Mob the DB migration part (CC @valerian ) and apply it on the preview DB
7. Verify that everything is OK and merge on main

2022-03-10 14:23 UTC, Jordanlelay commented
Closed, will be integrated in #913

2022-03-10 14:23 UTC, closed without merging