Fix user not disconnected when not found in database
labelflow/labelflow pull request #964
Opened 2022-03-18 10:25 UTC by Jordanlelay

## Work performed

- Fix user not disconnected when not found in database

## Resolved issues

Closes #883

2022-03-18 10:28 UTC, bbenoist requested changes

2022-03-18 10:28 UTC, bbenoist commented on typescript/web/src/hooks/use-user.tsx
> +  if (error) {
The handling should be more selective and keep the other errors follow the usual procedure.

2022-03-21 15:57 UTC, bbenoist requested changes

2022-03-23 10:32 UTC, bbenoist approved these changes
Code looks good to me 👍  Placed at the correct location!

2022-03-23 10:33 UTC, bbenoist commented
@valerian is doing functional tests and will approve and eventually merge the PR if OK 🚀

2022-03-25 16:47 UTC, nicOwlas commented
Functional test works perfectly 👍

2022-03-28 09:07 UTC, valerian approved these changes

2022-03-28 09:14 UTC, merged